"""Versioned incident contracts (schemas) used across the system.

These models are intentionally defined *before* any AI, Prometheus, or Kubernetes tooling,
so every node and tool shares the same stable object contracts.
"""

from incident_agent.contracts.llm import (
    BLOCKED_CONTROL_KEYS,
    AdvisoryEvidenceRequestCandidate,
    AdvisoryHypothesisCandidate,
    LLMSuggestion,
    LLMSuggestionRequest,
    LLMSuggestionResponse,
    SuggestionIngestionResult,
    SuggestionKind,
    SuggestionRejection,
    SuggestionStage,
)
from incident_agent.contracts.models import (
    Alert,
    Approval,
    ConfidenceScore,
    Diagnosis,
    Evidence,
    EvidenceRequest,
    EvidenceResult,
    ExecutionPlan,
    ExecutionResult,
    FixAction,
    FixActionType,
    FixPlan,
    Hypothesis,
    HypothesisVerification,
    IncidentState,
    Observations,
    OutcomeVerification,
    RemediationOption,
    RemediationPurpose,
    ResolutionAssessment,
    ResourceRef,
    RiskLevel,
    ValidationResult,
    ValidationVerdict,
)

__all__ = [
    "Alert",
    "AdvisoryEvidenceRequestCandidate",
    "AdvisoryHypothesisCandidate",
    "Approval",
    "BLOCKED_CONTROL_KEYS",
    "ConfidenceScore",
    "Diagnosis",
    "Evidence",
    "EvidenceRequest",
    "EvidenceResult",
    "ExecutionPlan",
    "ExecutionResult",
    "FixAction",
    "FixActionType",
    "FixPlan",
    "Hypothesis",
    "HypothesisVerification",
    "IncidentState",
    "Observations",
    "OutcomeVerification",
    "LLMSuggestion",
    "LLMSuggestionRequest",
    "LLMSuggestionResponse",
    "RemediationOption",
    "RemediationPurpose",
    "ResolutionAssessment",
    "ResourceRef",
    "RiskLevel",
    "SuggestionIngestionResult",
    "SuggestionKind",
    "SuggestionRejection",
    "SuggestionStage",
    "ValidationVerdict",
    "ValidationResult",
]

